# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

if [ -f ~/.custom_bashrc ]; then
        . ~/.custom_bashrc
fi

export PATH=/usr/local/bin:$PATH

# added by Anaconda3 4.2.0 installer
export PATH="/Users/Anthony/anaconda/bin:$PATH"
