export PYTHONSTARTUP="$HOME/.pythonrc"

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

loc=~/.local-aliases
alias ae='mvim $loc'   # Alias edit
alias ar='source $loc' # Alias reload
ar

alias activate="source ./venv/bin/activate"
alias mk_venv="python3 -m venv venv"

set -o vi
