gpip(){
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
export PYTHONSTARTUP="$HOME/.pythonrc"
export JAVA_HOME=`/usr/libexec/java_home -v '1.8*'`

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

loc=~/.zsh-aliases
alias ae='mvim $loc'   # Alias edit
alias ar='source $loc' # Alias reload
ar
