export PYTHONSTARTUP="$HOME/.pythonrc"

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

loc=~/.local-aliases
alias ae='mvim $loc'   # Alias edit
alias ar='source $loc' # Alias reload
if [ -f "$loc" ] ; then
  ar
fi

alias activate="source ./venv/bin/activate"
alias mk_venv="python3 -m venv venv"

set -o vi

export PATH=~/.config/emacs/bin:$PATH
